name: TZ Watcher (requests brute-decoder)

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        default: false
      debug:
        type: boolean
        default: true
      test_ping:
        type: boolean
        default: false
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Run watcher
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}
          WATCH_TERMS: ${{ vars.WATCH_TERMS }}
          DEBUG: ${{ github.event.inputs.debug }}
          FORCE_SEND: ${{ github.event.inputs.force }}
          TEST_PING: ${{ github.event.inputs.test_ping }}
        run: python watcher_requests.py
