name: Terror Zone Alerts

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual runs

permissions:
  contents: write           # allow commits to repo

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # needed to push changes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}
        run: python scrape_tz.py

      - name: Stage cache file
        run: git add tz_alert_cache.json

      - name: Save cache
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update TZ alert cache"
          skip_dirty_check: true
