name: Terror Zone Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:
    inputs:
      FORCE_DISCORD:
        description: "Force sending Discord alert regardless of checks"
        type: boolean
        default: false
      SEND_ALL_INITIALS:
        description: "Send all initial alerts for watchlist zones (test mode)"
        type: boolean
        default: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}
          FORCE_DISCORD: ${{ github.event.inputs.FORCE_DISCORD }}
          SEND_ALL_INITIALS: ${{ github.event.inputs.SEND_ALL_INITIALS }}
        run: python scrape_tz.py
