name: Terror Zone Alerts

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual runs
    inputs:
      force_discord:
        description: "Force Discord ping (ignore cache)"
        required: false
        type: boolean

permissions:
  contents: write           # allow commits to repo

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # needed to push changes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}
          FORCE_DISCORD: ${{ github.event.inputs.force_discord }}
        run: python scrape_tz.py

      - name: Check if cache changed
        id: cache_check
        run: |
          if git diff --quiet tz_alert_cache.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Stage cache file
        if: steps.cache_check.outputs.changed == 'true'
        run: git add tz_alert_cache.json

      - name: Save cache
        if: steps.cache_check.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update TZ alert cache"
          skip_dirty_check: true
